### PR TITLE
Fix images

### PR DESCRIPTION
**Pull request by divayprakash**
I found that all the image links in the markdown files in the `en/` directory were broken and so just fixed it quickly!

### CODE REVIEW

**Comment by ilabdsf** [comment]
@divayprakash
This book is expected to be compiled to ePUB or PDF with Makefile, which has `copyimg` rule to copy images where they should be.

**Comment by pvorb** [comment]
@ilabdsf is right. ePUB and PDF are the main purpose of this repo. Of course it would be nice if images also were shown on GitHub, but that's secondary.

**Comment by ilabdsf** [comment]
@divayprakash It can be accepted if you fix it without breaking ePUB and PDF builds.

**Comment by divayprakash** [comment]
@ilabdsf Working on it!

**Pull request closed without merging**
